/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class ListaPerfumes extends javax.swing.JFrame {
    ArrayList listaPerf;
    /**
     * Creates new form ListaPerfumes
     */
    public ListaPerfumes() {
        initComponents();
        listaPerf = new ArrayList();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLista = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btListar = new javax.swing.JButton();
        btOrdenar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPerfume = new javax.swing.JTextField();
        btExcluir = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("Lista Perfumes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 440, 95));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Perfume:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        txtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 440, -1));

        jScrollPane1.setForeground(new java.awt.Color(153, 153, 255));

        txtLista.setColumns(20);
        txtLista.setRows(5);
        jScrollPane1.setViewportView(txtLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 560, 330));

        btSalvar.setBackground(new java.awt.Color(0, 0, 0));
        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-salvar-48.png"))); // NOI18N
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 60, 60));

        btEditar.setBackground(new java.awt.Color(0, 0, 0));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-lápis-50.png"))); // NOI18N
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 60, 60));

        btListar.setBackground(new java.awt.Color(0, 0, 0));
        btListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-lista-de-ingredientes-50.png"))); // NOI18N
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });
        jPanel1.add(btListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 60, 60));

        btOrdenar.setBackground(new java.awt.Color(0, 0, 0));
        btOrdenar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-ordem-alfabética-50.png"))); // NOI18N
        btOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarActionPerformed(evt);
            }
        });
        jPanel1.add(btOrdenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 60, 60));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Pesquisar:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 150, 60));

        txtPerfume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPerfumeActionPerformed(evt);
            }
        });
        jPanel1.add(txtPerfume, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 440, -1));

        btExcluir.setBackground(new java.awt.Color(0, 0, 0));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-excluir-lixeira-50.png"))); // NOI18N
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 60, 60));

        btPesquisar.setBackground(new java.awt.Color(0, 0, 0));
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-pesquisar-50.png"))); // NOI18N
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 60, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaActionPerformed

    private void txtPerfumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPerfumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPerfumeActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        listaPerf.add(txtPerfume.getText());
        JOptionPane.showMessageDialog(null, "Salvo com sucesso");
        txtPerfume.setText(null);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        int i;
        i = Integer.parseInt(JOptionPane.showInputDialog("Digite o número do perfume para excluir:"));
        if (listaPerf.isEmpty()){
            JOptionPane.showMessageDialog(null, "Lista vazia xiru");
        }else{
            if ((i-1) >= 0 && (i-1) < listaPerf.size()){
                listaPerf.remove(i-1);
                JOptionPane.showMessageDialog(null, "Removido com sucesso");
                btListarActionPerformed(evt);
            }else{
                JOptionPane.showMessageDialog(null, "Não existe :/");
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed

        
        String listaPerfumesTexto = "";

        for (int c = 0; c < listaPerf.size(); c++){
            listaPerfumesTexto += (c + 1) + ". " + listaPerf.get(c) + "\n";
        }

        if (!listaPerfumesTexto.isEmpty()){
            txtLista.setText(listaPerfumesTexto);
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum perfume na lista");
        }
    }//GEN-LAST:event_btListarActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        int i;
        i = Integer.parseInt(JOptionPane.showInputDialog("Digite o número do perfume:"));
        String nome = JOptionPane.showInputDialog("Digite o novo nome do perfume:");
        if((i-1) >= 0 && (i-1) < listaPerf.size()){
            listaPerf.set((i-1),nome);
            JOptionPane.showMessageDialog(null, "Renomeado");
            btListarActionPerformed(evt);
        }else{
            JOptionPane.showMessageDialog(null, "Inválido");
        }
    }//GEN-LAST:event_btEditarActionPerformed
    private void ordenarLista() {
        Collections.sort(listaPerf);
    }
    private void btOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarActionPerformed
        ordenarLista();
        btListarActionPerformed(evt);
    }//GEN-LAST:event_btOrdenarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        String pesquisa = txtPesquisa.getText();
        boolean encontrado = false;

        for (int c = 0; c < listaPerf.size(); c++){
            if (listaPerf.get(c).equals(pesquisa)){
                JOptionPane.showMessageDialog(null, "Este perfume existe de fato");
                encontrado = true;
                break;
            }
        }
        if (!encontrado){
            JOptionPane.showMessageDialog(null, "Este perfume não existe mano.");
        } 
    }//GEN-LAST:event_btPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaPerfumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaPerfumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaPerfumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaPerfumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaPerfumes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btOrdenar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtLista;
    private javax.swing.JTextField txtPerfume;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
